---
site:
  title: Starky's club
backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: static/img
public_folder: "/img"
collections:
  - name: locale
    label: Locale
    widget: list
    folder: static/locale
    editor:
      preview: false
    fields:
      - name: title
        label: Name
      - name: code
        label: Code
  - name: config
    label: General
    folder: static/config
    editor:
      preview: false
    fields:
      - label: Locale
        name: locale
        widget: relation
        collection: locale
        searchFields:
          - title
          - code
        displayFields:
          - title
        valueField: code
      - label: Title
        name: title
      - label: Contact
        name: contact
        widget: object
        fields:
          - label: Contact person
            name: contactPerson
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Role
                name: role
                widget: string
              - label: Email
                name: email
                widget: string
              - label: Phone
                name: phone
                widget: string
              - label: LinkedIn
                name: linkedIn
                widget: string
              - label: Image
                name: image
                widget: image
          - label: Address
            name: address
            widget: object
            fields:
              - label: GPS
                name: gps
                widget: string
              - label: Street
                name: street
                widget: string
              - label: City
                name: city
                widget: string
              - label: ZIP
                name: zip
                widget: string
      - label: Footer
        name: footer
        widget: object
        fields:
          - label: Copy
            name: copy
            widget: string
          - label: Social
            name: social
            widget: list
            fields:
              - label: Link
                name: link
                widget: string
              - label: Image
                name: image
                widget: image
  - name: pages
    label: Pages
    files:
      - file: static/pages/index-cs.md
        label: Landing Page CS
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: IndexPage
          - label: Locale
            name: locale
            widget: hidden
            default: cs
          - label: Title
            name: title
            widget: string
            required: true
          - label: Subheading
            name: subheading
            widget: string
            required: true
          - label: Hero
            name: hero
            widget: file
            required: true
          - label: News
            name: news
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Description
                    name: description
                    widget: text
          - label: Clients
            name: clients
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
          - label: What we do
            name: work
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Services
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
                  - label: Description
                    name: description
                    widget: text
          - label: References
            name: references
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Subtitle (type)
                    name: subtitle
                    widget: string
                  - label: Description
                    name: description
                    widget: text
                  - label: Image
                    name: image
                    widget: image
          - label: Technologies
            name: technologies
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
      - file: static/pages/index-en.md
        label: Landing Page EN
        name: index-en
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: IndexPage
          - label: Locale
            name: locale
            widget: hidden
            default: cs
          - label: Title
            name: title
            widget: string
            required: true
          - label: Subheading
            name: subheading
            widget: string
            required: true
          - label: Hero
            name: hero
            widget: file
            required: true
          - label: News
            name: news
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Description
                    name: description
                    widget: text
          - label: Clients
            name: clients
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
          - label: What we do
            name: work
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Services
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
                  - label: Description
                    name: description
                    widget: text
          - label: References
            name: references
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Subtitle (type)
                    name: subtitle
                    widget: string
                  - label: Description
                    name: description
                    widget: text
                  - label: Image
                    name: image
                    widget: image
          - label: Technologies
            name: technologies
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
  - name: blog
    label: Blog
    folder: static/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: BlogPost
      - label: Locale
        name: locale
        widget: relation
        collection: locale
        searchFields:
          - title
          - code
        displayFields:
          - title
        valueField: code
      - label: Title
        name: title
        widget: string
        required: true
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Image
        name: image
        widget: image
