---
site:
  title: Starky's club
backend:
  name: bitbucket
  repo: starkysclub/starkys-fe
  branch: master
  base_url: http://starkysnetlify-env-1.q4aqw953v3.us-east-2.elasticbeanstalk.com/
media_folder: static/img
public_folder: "/img"
collections:
  - name: locale
    label: Locale
    widget: list
    folder: src/locale
    create: true
    fields:
      - name: title
        label: Name
      - name: code
        label: Code
  - name: text
    label: Text
    folder: src/locale/texts
    create: true
    fields:
      - label: Locale
        name: locale
        widget: relation
        collection: locale
        searchFields:
          - title
          - code
        displayFields:
          - title
        valueField: code
      - label: Key
        name: string
        widget: string
        required: true
      - label: Title
        name: title
        widget: string
        required: true
  - name: config
    label: General
    folder: src/config
    create: true
    fields:
      - label: Locale
        name: locale
        widget: relation
        collection: locale
        searchFields:
          - title
          - code
        displayFields:
          - title
        valueField: code
      - label: Title
        name: title
      - label: Contact
        name: contact
        widget: object
        fields:
          - label: Contact person
            name: contactPerson
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Role
                name: role
                widget: string
              - label: Email
                name: email
                widget: string
              - label: Phone
                name: phone
                widget: string
              - label: LinkedIn
                name: linkedIn
                widget: string
              - label: Image
                name: image
                widget: image
          - label: Address
            name: address
            widget: object
            fields:
              - label: GPS
                name: gps
                widget: string
              - label: Street
                name: street
                widget: string
              - label: City
                name: city
                widget: string
              - label: ZIP
                name: zip
                widget: string
      - label: Footer
        name: footer
        widget: object
        fields:
          - label: Copy
            name: copy
            widget: string
          - label: Social
            name: social
            widget: list
            fields:
              - label: Link
                name: link
                widget: string
              - label: Image
                name: image
                widget: image
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Locale
            name: locale
            widget: relation
            collection: locale
            searchFields:
              - title
              - code
            displayFields:
              - title
            valueField: code
          - label: Title
            name: title
            widget: string
            required: true
          - label: Subheading
            name: subheading
            widget: string
            required: true
          - label: Hero
            name: hero
            widget: file
            required: true
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Logo
                name: logo
                widget: image
              - label: Description
                name: description
                widget: text
              - label: Link
                name: link
                widget: string
          - label: What we do
            name: work
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Services
                name: services
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
                  - label: Description
                    name: description
                    widget: text
          - label: Technologies
            name: technologies
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Logos
                name: logos
                widget: list
                fields:
                  - label: Logo
                    name: logo
                    widget: image
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Locale
        name: locale
        widget: relation
        collection: locale
        searchFields:
          - title
          - code
        displayFields:
          - title
        valueField: code
      - label: Title
        name: title
        widget: string
        required: true
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Image
        name: image
        widget: image
  - name: reference
    label: References
    folder: src/pages/reference
    create: true
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: reference-page
      - label: Locale
        name: locale
        widget: relation
        collection: locale
        searchFields:
          - title
          - code
        displayFields:
          - title
        valueField: code
      - label: Title
        name: title
        widget: string
        required: true
      - label: Type
        name: type
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: External link
        name: link
        widget: string
      - label: Image
        name: image
        widget: image
